spring:
  profiles:
    active: ${profile}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: 1