spring:
  profiles:
    active: ${profile}

cloud:
  aws:
    s3:
      bucket: main-005-image
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}